### ISSUE TITLE
CEM questions

### ISSUE THREAD

**Issue by victorca25** [YuvalBahat/Explorable-Super-Resolution#10]
Hello! 

I'm trying out the CEM in isolation with a regular ESRGAN trained model (using the official pretrain model as benchmark), but I have two questions. 

When wrapping the network with CEM, I run out of VRAM, which doesn't happen with the model normally, but I really can't see what operation could be consuming the additional memory. Any suggestion for what could be happening?

Also, I noticed something similar happens in the paper's example, but when compared to the regular ESRGAN model upscale, while the wrapped result does seem sharper, it results in ringing around the edges:

![image](https://user-images.githubusercontent.com/41912303/105212657-08e90e00-5b4e-11eb-8c4e-954eee82b8db.png)

Here left is LR, middle is regular ESRGAN, right is ESRGAN wrapped with CEM.

I imagine this ringing is reduced if the model is now trained using CEM, but same as the previous question, any additional recommendations?

I will test it out with other models besides RRDB as well, its an interesting way to combine internal and external learning, but I would like to find if I'm doing something wrong.

Cheers and thanks for the great work!

**Comment by YuvalBahat** [comment]
Hi,

Thanks for reaching out, and I'm glad you are trying our CEM independently for wrapping other pretrained SR models.

As for the VRAM issue, I actually don't know what could be the reason for that. The CEM only introduces 3 additional filtering modules, so I don't think it should consume a lot of memory. Perhaps you can try to debug it to understand which operation causes this memory exhaustion. Let me know if I can be of any help with that.

Regarding the ringing effects - this depends on their location in the image. Near image borders, this could be the result of border effects by the CEM filters. However, in the example you attached, this ringing most likely stems from the combination of low frequency and high frequency content that's happening within the CEM, and as you said would probably be eliminated after some fine tuning of the pretrained model.

One `sanity check' you can perform to verify that the CEM works properly is to downscale the SR image (using imresize_CEM.imresize(), to make sure you are using the same downsampling kernel) and verify that the result is identical to the LR input, except near image borders.

Please let me know if there is anything else I can do to help.
Yuval

**Comment by YuvalBahat** [comment]
For some reason I assumed you were experimenting with an LR image you created yourself, by downscaling an HR image. Please note that when using KernelGAN (or any other kernel estimation method) to estimate the downscaling kernel corresponding to a **real** LR image, those ringing artifacts by the CEM may also stem from inaccurate kernel estimation.

**Comment by victorca25** [comment]
Aha! I see. I'll try with multiple kernel estimations to see how it changes. Thanks!

**Comment by victorca25** [comment]
Hello again! Testing with multiple different kernel estimations did not change the ringing substantially, but I found that changing the lower_magnitude_bound value changes it a lot. Increasing it progressively from 0.1 to 0.3 makes it less noticeable in each step. My guess right now is that the ringing is introduced during the fft, but I'll continue testing.

**Comment by YuvalBahat** [comment]
That's interesting, and it makes sense. This means the estimated kernels zero out some low frequency content. Inverting these zero-valued parts of the kernel's FFT when calculating (HH^T)^-1 probably results in very high values, which in turn cause these ringing artifacts.

To isolate this issue, you may want to synthesize LR images yourself, by downsampling them (using the imresize function in imresize_CEM, which optionally takes a downsampling kernel) using kernels of different widths (corresponding to different amount of blurs), and then feeding these synthetic images into the CEM. I would expect narrow kernels (inducing little to no blur) to result in less ringing artifacts than images created using wide (blur-inducing) kernels.

**Comment by victorca25** [comment]
I tested some combinations and I think you are correct about the inverse hTh values. Here are some examples of the tests:

With estimated kernels:
1) with lower_magnitude_bound = 0.01:
    size_k = 17: (same up to 33, bounded by Center_Mass's 12x12 output):
    inv_hTh min: -22.849794
    inv_hTh max: 40.391304
   
    size_k = 13:
    inv_hTh min: -21.916033
    inv_hTh max: 37.11187
    
    size_k = 9:
    inv_hTh min: -7.506223
    inv_hTh max: 11.269619

2) with lower_magnitude_bound = 0.3:
    size_k = 17:
    inv_hTh min: -0.17581916
    inv_hTh max: 2.6446378

With default cubic kernel:
  with lower_magnitude_bound = 0.01:
    size_k = 17:
    inv_hTh min: -0.27087596
    inv_hTh max: 1.554791

An alternative I found to reduce the ringing is by processing the difference between the CEM output and the original model's output with a guided filter, which preserve edges and reduces artifacts including the ringing, and adding that to the original model's output (by configuring the filter, it also becomes a tuneable parameter for inference). I find CEM's enforcement of low frequency information (such as colors) to be very interesting for multiple uses I'm testing. 

For use during training, is it recommended to use the LR images' estimated kernels or the default kernel?

**Comment by YuvalBahat** [comment]
Hi,
The problem with inverting HH^T arises when there are **FFT coefficients** of HH^t whose **magnitude is zero**. That's because inverting this filter means taking the inverse in the Fourier domain, which in such case results in dividing by zero. That's why we use the lower_magnitude_bound threshold. Do the min and max value you reported correspond to the FFT of the filter, or to the filter itself?

Your alternative solution of using a guided filter sounds interesting. However, note that processing the output of the CEM means the output would no longer be consistent with the LR input. In a way, this may be missing the purpose of using the CEM in the first place.

**Comment by victorca25** [comment]
In this case the min and max values belong to "self.inv_hTh", after the FFT, the inversion and taking the real part of the number. What I noticed is that while they are not infinite values, higher magnitudes correspond to more ringing, so it must be dividing by values very close to zero. Both reducing the kernel size and increasing the lower_magnitude_bound decrease these magnitudes, as well as the ringing. Also, the ringing doesn't happend with the default kernel and the magnitudes are small.

**Comment by YuvalBahat** [comment]
I see, and it makes sense.
Thanks for updating me.

**Comment by victorca25** [comment]
Thanks for your help! I understand it better now and will start testing it for training. Just to validate, since the CEM has no trainable parameters and it's initialized with the model, it isn't really required to save the wrapped architecture, it can be unwrapped before saving and kept with the original model's parameters, is that correct?

Also, something unrelated, in the code and configuration files, there's a "ShiftInvariant_Loss" option, but the function doesn't exist in the repository. Is it required?

**Comment by YuvalBahat** [comment]
Hi,

Regarding saving the parameters - you are correct, there is no need to save the CEM parameters, as they are computed upon constructing the CEM. Note that the CEM filters are computed as a function of the assumed downsampling kernel corresponding to the LR-HR image pairs. which means the CEM should be re-constructed whenever switching from one kernel to another.

As for the ShiftInvariant_Loss, this is just something we tried and eventually did not use, so you can ignore it.
Good luck with the training, and let me know if you encounter any additional issues.
