### ISSUE TITLE
no module named jpeg2dct

### ISSUE THREAD

**Issue by nan-rock** [YuvalBahat/Explorable-Super-Resolution#7]
thanks sir for interesting paper..I am getting an error  related to module jpeg2dct.. can you please let me know. Is it being downloaded from some repository since it don't seem to be pytorch or python function.

**Comment by YuvalBahat** [comment]
Thanks for your message.
If I understand correctly, you are getting an import error. Can you say which file tries to import this jpeg2dct?

**Comment by nan-rock** [comment]
python GUI.py -opt ./options/test/GUI_SR.json   while running this, i got the error.

**Comment by YuvalBahat** [comment]
I removed this import, as this module is unnecessary at this point. Thanks a lot.
